[versions]
agp = "9.3.0"
kotlin = "2.4.10"
android-minSdk = "24"
android-compileSdk = "36"
vanniktechMavenPublish = "0.37.0"
compose-version = "1.11.1"
lets-plot-kotlin = "4.15.0"
lets-plot = "4.8.2"
lets-plot-platf = "4.11.0"
dokka = "2.2.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
lets-plot-kotlin-jvm = { module = "org.jetbrains.lets-plot:lets-plot-kotlin-jvm", version.ref = "lets-plot-kotlin" }
lets-plot-image-export = { module = "org.jetbrains.lets-plot:lets-plot-image-export", version.ref = "lets-plot" }
lets-plot-platf-awt = { module = "org.jetbrains.lets-plot:platf-awt", version.ref = "lets-plot-platf" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }